spring:
  redis:
    database: 1
    host: 192.168.237.133
    password:
    port: 6379
    timeout: 20000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///demo
    username: root
    password: root
logging:
  level:
    com.majorco.mapper.DelayTaskMapper: debug